version: "3"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: projectdb
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    ports:
      - "5432:5432" # Map container port to host port
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
volumes:
  postgres_data:
